### PR TITLE
Issue #40

### PR DESCRIPTION
**Pull request by muyiwaolurin**
Update

### CODE REVIEW

**Comment by muyiwaolurin** [comment]
result

**Comment by muyiwaolurin** [comment]
decimalPlaces = 0; 

result2

**Comment by benkeen** [comment]
Thanks, @muyiwaolurin! I'll take a look at this this weekend. :)

**Comment by chihlee** [comment]
This looks very useful!

**Comment by chihlee** [comment]
After a second look, it does not guarantee that the values sum up to 100:
E.g.
(50.5).toFixed(0)
"51"
(49.5).toFixed(0)
"50"

or
(20.25).toFixed(1)
"20.3"
(20.75).toFixed(1)
"20.8"
(59).toFixed(1)
"59.0"

I don't have a better solution at this moment though. I can live with calling toFixed() for now unless someone comes up with a better solution.

**Comment by muyiwaolurin** [comment]
Thanks @chihlee !

**Comment by benkeen** [comment]
Sorry I didn't have time to look at this last weekend - I'm afraid I'm going out of town for the next 2 weeks, but I'll look at it when I get back. :)

**Pull request closed without merging**
