### PR TITLE
Compatibility with D3js v4

### PR DESCRIPTION
**Pull request by jcisio**
These minimal changes are needed to work with D3 4.x (https://github.com/benkeen/d3pie/issues/109)

### CODE REVIEW

**Comment by jcisio** [comment]
I'm working on the source file.

**Comment by jcisio** [comment]
Sorry this PR does not fully work. Some changes are still to be done (e.g. d3.svg.line() call when the "lines" option is enabled). I don't use this feature and after a few tries, I don't know how to port it to v4 neither. Feel free to update this PR with more fixes.

**Comment by jcisio** [comment]
I happened to need the "lines" option, so now I've fixed it.

**Comment by benkeen** [comment]
Brilliant, thanks @jcisio! Sorry for not merging this in sooner - I've been focused on other script. I'll take a look at this closer this weekend before merging, but the PR looks good at a quick glance.

**Pull request merged**
